language: c
sudo: false
cache:
  directories:
    - $HOME/.cabsnap
    - $HOME/.cabal/packages
    - $HOME/tools
before_cache:
  - rm -f $HOME/.cabal/packages/hackage.haskell.org/build-reports.log
  - rm -f $HOME/.cabal/packages/hackage.haskell.org/00-index.tar
before_install: source travis/setup.sh
install: travis/install.sh
script: travis/script.sh
matrix:
  include:
    - env: GHCVER=7.2.2 CABALVER=1.18
      compiler: ghc-7.2.2
      addons: {apt: {packages: [cabal-install-1.18, ghc-7.2.2, alex-3.1.4, happy-1.19.5], sources: [hvr-ghc]}}
    - env: GHCVER=7.4.2 CABALVER=1.24
      compiler: ghc-7.4.2
      addons: {apt: {packages: [cabal-install-1.24, ghc-7.4.2, alex-3.1.4, happy-1.19.5], sources: [hvr-ghc]}}
    - env: GHCVER=7.6.3 CABALVER=1.24
      compiler: ghc-7.6.3
      addons: {apt: {packages: [cabal-install-1.24, ghc-7.6.3, alex-3.1.4, happy-1.19.5], sources: [hvr-ghc]}}
    - env: GHCVER=7.8.4 CABALVER=1.24
      compiler: ghc-7.8.4
      addons: {apt: {packages: [cabal-install-1.24, ghc-7.8.4, alex-3.1.4, happy-1.19.5], sources: [hvr-ghc]}}
    - env: GHCVER=7.10.3 CABALVER=1.24
      compiler: ghc-7.10.3
      addons: {apt: {packages: [cabal-install-1.24, ghc-7.10.3, alex-3.1.4, happy-1.19.5], sources: [hvr-ghc]}}
    - env: GHCVER=8.0.1 CABALVER=1.24
      compiler: ghc-8.0.1
      addons: {apt: {packages: [cabal-install-1.24, ghc-8.0.1, alex-3.1.7, happy-1.19.5], sources: [hvr-ghc]}}
    - env: GHCVER=8.2.2 CABALVER=2.0
      compiler: ghc-8.2.2
      addons: {apt: {packages: [cabal-install-2.0, ghc-8.2.2, alex-3.1.7, happy-1.19.5], sources: [hvr-ghc]}}
    - env: GHCVER=8.4.4 CABALVER=2.2
      compiler: ghc-8.4.4
      addons: {apt: {packages: [cabal-install-2.2, ghc-8.4.4, alex-3.1.7, happy-1.19.5], sources: [hvr-ghc]}}
    - env: GHCVER=8.6.5 CABALVER=2.4
      compiler: ghc-8.6.5
      addons: {apt: {packages: [cabal-install-2.4, ghc-8.6.5, alex-3.1.7, happy-1.19.5], sources: [hvr-ghc]}}
    - env: GHCVER=8.8.3 CABALVER=3.0 ROOT=1 V2=1
      compiler: ghc-8.8.3
      addons: {apt: {packages: [cabal-install-3.0, ghc-8.8.3, alex-3.1.7, happy-1.19.5], sources: [hvr-ghc]}}
    - env: GHCVER=8.10.1 CABALVER=3.2 V2=1
      compiler: ghc-8.10.1
      addons: {apt: {packages: [cabal-install-3.2, ghc-8.10.1, alex-3.1.7, happy-1.19.5], sources: [hvr-ghc]}}
    - env: GHCVER=head CABALVER=head ALLOW_NEWER="template-haskell" V2=1
      compiler: ghc-head
      addons: {apt: {packages: [cabal-install-head, ghc-head, alex-3.1.7, happy-1.19.5], sources: [hvr-ghc]}}
  allow_failures:
    - compiler: ghc-head
  fast_finish: true
